# Generated by Django 4.1.3 on 2022-11-24 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_logout',
            field=models.DateField(null=True, verbose_name='last logout'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='updated at'),
        ),
    ]
